name = "spp"
compatibility_date = "2024-11-20"

[build]
command = "npx @opennextjs/cloudflare build"

[site]
bucket = ".open-next/static"
entry-point = ".open-next/worker"

[vars]
NODE_VERSION = "18"
NEXT_TELEMETRY_DISABLED = "1"
